# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: vadafi-postgres
    environment:
      POSTGRES_USER: vadafi-admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vadafi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  postgres_data:

